title: Conversor Temperatura Java
description: Sistema de conversão de escalas térmicas (Celsius e Fahrenheit) desenvolvido em Java
theme: jekyll-theme-cayman

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - README.md
